"""Malpedia-backed actor / malware canonicalization.

After the LLM produces an ``EnrichedArticle``, we look up every extracted
threat-actor and malware name against the bundled Malpedia snapshot. If we
find a match (e.g. "Midnight Blizzard" -> "APT29") we rewrite the entity
to the canonical name and, when known, fill in the MITRE ID.

This is *non-destructive* by design:
  * If Malpedia does not know the name, we leave the LLM's output alone.
  * We never override an explicit, valid MITRE ID the model already set.
  * We dedupe by canonical name so two aliases of the same actor collapse
    into one entry instead of staying as duplicates.

Data file: ``data/malpedia.json.gz`` (gzipped JSON to keep the package
size sane). Regenerated by ``scripts/fetch_malpedia.py``.
"""
from __future__ import annotations

import gzip
import json
import logging
import re
from functools import lru_cache
from pathlib import Path
from typing import Iterable

log = logging.getLogger(__name__)

_DATA_PATH = Path(__file__).resolve().parent / "data" / "malpedia.json.gz"


def _normalize_alias(s: str) -> str:
    """Mirror of scripts/fetch_malpedia.py::_normalize_alias.

    Lowercase + collapse whitespace + strip dashes so 'APT 29', 'apt29',
    'APT-29', 'APT\u201129' all collide on the same key.
    """
    s = (s or "").strip().lower()
    s = re.sub(r"[\s\-\u2010-\u2015]+", " ", s)
    s = re.sub(r"\s+", " ", s)
    return s.strip()


@lru_cache(maxsize=1)
def _catalog() -> dict:
    """Return the full malpedia data, or an empty stub if the file is missing
    or corrupt. Never raises -- enrichment must keep working without it."""
    if not _DATA_PATH.is_file():
        log.warning(
            "Malpedia data file not found at %s; canonicalization disabled.",
            _DATA_PATH,
        )
        return {"actors": {}, "families": {}}
    try:
        with gzip.open(_DATA_PATH, "rt", encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:
        log.exception("Failed to load Malpedia data: %s", exc)
        return {"actors": {}, "families": {}}


def lookup_actor(name: str) -> dict | None:
    if not name:
        return None
    return _catalog().get("actors", {}).get(_normalize_alias(name))


def lookup_family(name: str) -> dict | None:
    if not name:
        return None
    return _catalog().get("families", {}).get(_normalize_alias(name))


def stats() -> dict:
    c = _catalog()
    return {
        "actors": len(c.get("actors", {})),
        "families": len(c.get("families", {})),
        "version": c.get("version"),
    }


# ---------------------------------------------------------------------------
# Post-processing helpers used by the enrichment worker
# ---------------------------------------------------------------------------

def canonicalize_actors(actors: list) -> tuple[list, list[str]]:
    """Rewrite a list of ThreatActorEntity-shaped dicts in place.

    Returns (new_list, additional_mitre_group_ids) where additional_mitre_group_ids
    is the set of G#### IDs we discovered through canonicalization that
    should be merged into entities.mitre_groups[].
    """
    if not actors:
        return [], []
    seen_canonical: dict[str, dict] = {}
    extra_group_ids: list[str] = []
    for raw in actors:
        if not isinstance(raw, dict):
            continue
        name = (raw.get("name") or "").strip()
        if not name:
            continue
        rec = lookup_actor(name)
        if rec:
            canonical = rec.get("canonical") or name
            mitre_id = rec.get("mitre_group_id")
            if mitre_id and not raw.get("mitre_group_id"):
                raw["mitre_group_id"] = mitre_id
                extra_group_ids.append(mitre_id)
            elif raw.get("mitre_group_id") and mitre_id:
                # both have one and they disagree -> trust the LLM's call
                # but still record the malpedia ID
                if raw["mitre_group_id"] != mitre_id:
                    extra_group_ids.append(mitre_id)
            # Rewrite display name to the canonical form. Keep the original
            # in `role` if there's no role yet, so the UI can show it.
            if canonical and canonical != name:
                raw.setdefault("role", f"alias of {name}")
                raw["name"] = canonical
        # Dedupe by canonical name (case-insensitive). If the same canonical
        # appears twice (e.g. LLM emitted both "APT29" and "Midnight
        # Blizzard"), keep the entry with higher confidence + a MITRE ID.
        key = _normalize_alias(raw["name"])
        existing = seen_canonical.get(key)
        if existing is None:
            seen_canonical[key] = raw
        else:
            if (raw.get("mitre_group_id") and not existing.get("mitre_group_id")) or (
                (raw.get("confidence") or 0) > (existing.get("confidence") or 0)
            ):
                seen_canonical[key] = raw
    return list(seen_canonical.values()), list(dict.fromkeys(extra_group_ids))


def canonicalize_malware(items: list) -> tuple[list, list[str]]:
    """Like canonicalize_actors but for MalwareEntity-shaped dicts."""
    if not items:
        return [], []
    seen_canonical: dict[str, dict] = {}
    extra_software_ids: list[str] = []
    for raw in items:
        if not isinstance(raw, dict):
            continue
        name = (raw.get("name") or "").strip()
        if not name:
            continue
        rec = lookup_family(name)
        if rec:
            canonical = rec.get("canonical") or name
            mitre_id = rec.get("mitre_software_id")
            if mitre_id and not raw.get("mitre_software_id"):
                raw["mitre_software_id"] = mitre_id
                extra_software_ids.append(mitre_id)
            if canonical and canonical != name:
                raw.setdefault("role", f"alias of {name}")
                raw["name"] = canonical
        key = _normalize_alias(raw["name"])
        existing = seen_canonical.get(key)
        if existing is None:
            seen_canonical[key] = raw
        else:
            if (raw.get("mitre_software_id") and not existing.get("mitre_software_id")) or (
                (raw.get("confidence") or 0) > (existing.get("confidence") or 0)
            ):
                seen_canonical[key] = raw
    return list(seen_canonical.values()), list(dict.fromkeys(extra_software_ids))


def merge_id_lists(*sources: Iterable[str]) -> list[str]:
    """Merge multiple ID lists into a single de-duplicated, order-preserving list."""
    out: list[str] = []
    seen: set[str] = set()
    for src in sources:
        if not src:
            continue
        for v in src:
            if v and v not in seen:
                seen.add(v)
                out.append(v)
    return out
