"""MITRE ATT&CK identifier validation, catalog access, and normalization.

Pharos uses MITRE's official identifier formats end-to-end so that entities
extracted by the lantern can be cross-referenced against the public ATT&CK
knowledge base (https://attack.mitre.org/).

Identifier formats:
    Group ID:        G####            e.g. G0016 (APT29)
    Software ID:     S####            e.g. S0154 (Cobalt Strike)
    Technique ID:    T####            e.g. T1566
    Sub-technique:   T####.###        e.g. T1566.001
    Tactic ID:       TA####           e.g. TA0001 (Initial Access)
    Mitigation ID:   M####            e.g. M1017
    Data source ID:  DS####           e.g. DS0029

In addition to format validation, this module loads a bundled snapshot of
the ATT&CK Enterprise tactics + techniques catalog from
``data/mitre_catalog.json`` so the lantern prompt can show the model the
list of valid IDs (with their human-readable names) and so we can validate
that LLM-emitted IDs actually exist in the catalog.

The bundled catalog is regenerated by ``scripts/fetch_mitre_catalog.py``.
We deliberately do NOT bundle Groups (G####) or Software (S####); the LLM
extracts those by name and we canonicalize via Malpedia post-hoc.
"""
from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

GROUP_RE = re.compile(r"^G\d{4}$")
SOFTWARE_RE = re.compile(r"^S\d{4}$")
TECHNIQUE_RE = re.compile(r"^T\d{4}(?:\.\d{3})?$")
TACTIC_RE = re.compile(r"^TA\d{4}$")
MITIGATION_RE = re.compile(r"^M\d{4}$")
DATA_SOURCE_RE = re.compile(r"^DS\d{4}$")

_CATALOG_PATH = Path(__file__).resolve().parent / "data" / "mitre_catalog.json"


def normalize(identifier: str) -> str:
    """Uppercase + strip; the canonical MITRE form."""
    return identifier.strip().upper()


def is_group(identifier: str) -> bool:
    return bool(GROUP_RE.match(normalize(identifier)))


def is_software(identifier: str) -> bool:
    return bool(SOFTWARE_RE.match(normalize(identifier)))


def is_technique(identifier: str) -> bool:
    return bool(TECHNIQUE_RE.match(normalize(identifier)))


def is_tactic(identifier: str) -> bool:
    return bool(TACTIC_RE.match(normalize(identifier)))


def is_mitigation(identifier: str) -> bool:
    return bool(MITIGATION_RE.match(normalize(identifier)))


def is_data_source(identifier: str) -> bool:
    return bool(DATA_SOURCE_RE.match(normalize(identifier)))


def parent_technique(technique_id: str) -> str:
    """Return the parent technique ID for a sub-technique, else the input."""
    norm = normalize(technique_id)
    if "." in norm:
        return norm.split(".", 1)[0]
    return norm


# ---------------------------------------------------------------------------
# Catalog access (bundled snapshot from MITRE/CTI)
# ---------------------------------------------------------------------------

@lru_cache(maxsize=1)
def _catalog() -> dict:
    """Load the bundled MITRE catalog JSON. Returns an empty stub on failure
    so missing data never crashes enrichment."""
    if not _CATALOG_PATH.is_file():
        return {"tactics": [], "techniques": [], "stats": {}}
    try:
        return json.loads(_CATALOG_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {"tactics": [], "techniques": [], "stats": {}}


def tactics() -> list[dict]:
    """Return the ordered list of MITRE Tactics. Each item has id/name/short_name."""
    return list(_catalog().get("tactics", []))


def techniques() -> list[dict]:
    """Return the full list of MITRE Techniques + Sub-techniques.
    Each item: {id, name, parent_id, tactics, is_subtechnique}.
    """
    return list(_catalog().get("techniques", []))


@lru_cache(maxsize=1)
def technique_ids() -> set[str]:
    return {t["id"] for t in techniques()}


@lru_cache(maxsize=1)
def tactic_ids() -> set[str]:
    return {t["id"] for t in tactics()}


@lru_cache(maxsize=1)
def technique_name(technique_id: str) -> str | None:
    for t in techniques():
        if t["id"] == technique_id:
            return t["name"]
    return None


def is_known_technique(technique_id: str) -> bool:
    """Tighter than ``is_technique``: also requires the ID to exist in the
    bundled catalog. Falls back to format-only validation if the catalog
    isn't loaded."""
    norm = normalize(technique_id)
    if not is_technique(norm):
        return False
    ids = technique_ids()
    if not ids:
        return True  # catalog not bundled, accept by format
    return norm in ids


def is_known_tactic(tactic_id: str) -> bool:
    norm = normalize(tactic_id)
    if not is_tactic(norm):
        return False
    ids = tactic_ids()
    if not ids:
        return True
    return norm in ids


def attack_url(identifier: str) -> str | None:
    """Return the canonical attack.mitre.org URL for a given identifier."""
    norm = normalize(identifier)
    if is_group(norm):
        return f"https://attack.mitre.org/groups/{norm}/"
    if is_software(norm):
        return f"https://attack.mitre.org/software/{norm}/"
    if is_technique(norm):
        if "." in norm:
            parent, sub = norm.split(".", 1)
            return f"https://attack.mitre.org/techniques/{parent}/{sub}/"
        return f"https://attack.mitre.org/techniques/{norm}/"
    if is_tactic(norm):
        return f"https://attack.mitre.org/tactics/{norm}/"
    if is_mitigation(norm):
        return f"https://attack.mitre.org/mitigations/{norm}/"
    if is_data_source(norm):
        return f"https://attack.mitre.org/datasources/{norm}/"
    return None
